name: xplore_prophecy
description: ''
version: 0.0.2
author: kundandombale@outlook.com
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: xploreprophecy
  parentArtefactID: kundandombaleoutlookcomteam
  buildSystem: wheel
  author: null
  createdAt: '2024-11-27 07:24:09'
pipelines:
  pipelines/pl_xplore_phrophecy_source_gem:
    name: pl_xplore_phrophecy_source_gem
    description: ''
    author: kundandombale@outlook.com
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-11-27 07:24:09'
    datasets:
      inputs:
      - datasets/ds_src_customers
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/ds_src_customers:
    name: ds_src_customers
    description: ''
    author: kundandombale@outlook.com
    createdAt: '2024-11-27 07:48:39'
    mode: batch
    physicalDatasets:
      ndev-fbr:
        fabricId: 19315
        datasetType: File
        description: ''
        author: kundandombale@outlook.com
        createdAt: '2024-11-27 07:48:39'
templates: {}
jobs:
  jobs/test_job:
    name: test_job
    description: ''
    fabricUID: 19315
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 1/1 * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/pl_xplore_phrophecy_source_gem
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2024-11-27 08:49:57'
    author: kundandombale@outlook.com
    models: []
    sqlProjects: []
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-11-27 07:24:09'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-11-27T07:24:09.020808Z'
  name: plibMaven
  version: 8.5.0
  id: '597375224'
  createdAt: '2024-11-27T07:24:09.020808Z'
  type: plibMaven
  enabled: true
  entity: Project
- modifiedAt: '2024-11-27T07:24:18.421Z'
  name: ProphecyLibsPython
  version: 1.9.24
  id: '956686375'
  createdAt: '2024-11-27T07:24:09.020808Z'
  type: plibPypi
  enabled: true
  entity: Project
  description: Default dependency for Prophecy Libs
  scope: Project
  editable: true
projectDependencies:
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-11-27 07:23:23'
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.35
    isDefault: true
    author: null
    createdAt: '2024-11-27 07:23:23'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
